# Generated by Django 5.0 on 2024-06-24 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="item",
        ),
        migrations.RemoveField(
            model_name="order",
            name="ordered_date",
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.product",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="Item",
        ),
    ]
